### ISSUE TITLE
NeoForge crash

### ISSUE THREAD

**Issue by DeeChael** [Traben-0/entity_sound_features#1]
The modloader version range is wrong in the neoforge.mods.toml
https://github.com/Traben-0/entity_sound_features/blob/master/neoforge/src/main/resources/META-INF/neoforge.mods.toml
![image](https://github.com/Traben-0/entity_sound_features/assets/63186003/55274b00-a2d4-4488-9a1c-d8939ba7024d)

**Comment by Traben-0** [comment]
:/ must have broken in the last build im sure it worked during testing

**Comment by Traben-0** [comment]
I'll hide the download for now

**Comment by DeeChael** [comment]
sorry but the mod still has the same problem in 0.3.1
the mod file is directly downloaded from Modrinth
![image](https://github.com/Traben-0/entity_sound_features/assets/63186003/94eb06c2-ad10-45b3-bb7d-084454d8b191)

**Comment by Traben-0** [comment]
Hmm, I'm certain it launched for me odd unless my launcher hasn't been replacing the old file

**Comment by Traben-0** [comment]
There was an issue on my end impacting the neoforge testing instances -_-

**Comment by Traben-0** [comment]
fixed for 0.4
