### ISSUE TITLE
Consistent crashes on the latest 1.21.3 build.

### ISSUE THREAD

**Issue by GrimPlayzs** [Traben-0/entity_sound_features#5]
Crash report: https://mclo.gs/5rrKf2O

**Comment by Traben-0** [comment]
can you tell me what you were doing, i cannot replicate this crash myself

**Comment by Firebolt360** [comment]
I think this is in relation to trial chambers and the spawners. I also experienced crashes.

**Comment by Traben-0** [comment]
I'll test that

**Comment by GrimPlayzs** [comment]
I'm not sure what I'm doing is causing it to crash. Even on a fresh instance on a SP word crashes the game as soon the world is loaded.

**Comment by Firebolt360** [comment]
That sounds similar to my issue. I load a new world, a few chunks load, the chunks stop loading, and I get kicked. Singleplayer world with default generation.

**Comment by GrimPlayzs** [comment]
Seems like any entity crashes the game. No matter what I do I can't stop it from crashing.

**Comment by Traben-0** [comment]
> Seems like any entity crashes the game. No matter what I do I can't stop it from crashing.

can i get your exact modlist with their file names and your game version and loader

**Comment by Traben-0** [comment]
also tell me where you downloaded ESF from

**Comment by Firebolt360** [comment]
Oh interesting. Well, I personally downloaded ESF through modrinth. It was the latest version for 1.21.3. This was the specific modpack and version I was running when I experienced the crashes:
https://modrinth.com/modpack/elixir/version/3.3.0-beta.7-1.21.3

**Comment by Traben-0** [comment]
fixed, it was a wrong file upload that apparently my system would not re-download as i had the correct file already on my end

**Comment by Traben-0** [comment]
curseforge might take a few minutes too verify the file but modrinth ahs the correct one
